<?php

use Illuminate\Database\Seeder;

class MaterialsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('materials')->delete();
        
        \DB::table('materials')->insert(array (
            0 => 
            array (
                'id' => 1,
                'created_at' => '2019-12-23 10:14:55',
                'updated_at' => '2019-12-23 10:14:55',
                'deleted_at' => NULL,
                'name' => 'برطمان كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 2,
                'max_order' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'created_at' => '2019-12-23 10:16:56',
                'updated_at' => '2019-12-23 10:16:56',
                'deleted_at' => NULL,
                'name' => 'عسل نوارة',
                'quantity_type' => 0,
                'type' => 0,
                'material_type_id' => 1,
                'max_order' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'created_at' => '2019-12-23 10:43:03',
                'updated_at' => '2019-12-23 10:43:03',
                'deleted_at' => NULL,
                'name' => 'عسل صحراوى',
                'quantity_type' => 0,
                'type' => 0,
                'material_type_id' => 1,
                'max_order' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'created_at' => '2019-12-24 15:23:55',
                'updated_at' => '2019-12-24 15:27:20',
                'deleted_at' => NULL,
                'name' => 'عسل حبة البركة محلي',
                'quantity_type' => 1,
                'type' => 0,
                'material_type_id' => 1,
                'max_order' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'created_at' => '2019-12-24 15:24:42',
                'updated_at' => '2019-12-24 15:26:48',
                'deleted_at' => NULL,
                'name' => 'عسل بردقوش محلي',
                'quantity_type' => 1,
                'type' => 0,
                'material_type_id' => 1,
                'max_order' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'created_at' => '2019-12-24 15:25:26',
                'updated_at' => '2019-12-24 15:27:06',
                'deleted_at' => NULL,
                'name' => 'عسل نوارة البرسيم محلي',
                'quantity_type' => 1,
                'type' => 0,
                'material_type_id' => 1,
                'max_order' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'created_at' => '2019-12-24 15:26:28',
                'updated_at' => '2019-12-24 15:26:56',
                'deleted_at' => NULL,
                'name' => 'عسل موالح محلي',
                'quantity_type' => 1,
                'type' => 0,
                'material_type_id' => 1,
                'max_order' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'created_at' => '2019-12-24 15:29:24',
                'updated_at' => '2019-12-24 15:29:24',
                'deleted_at' => NULL,
                'name' => 'عسل بلح محلي',
                'quantity_type' => 1,
                'type' => 0,
                'material_type_id' => 1,
                'max_order' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'created_at' => '2019-12-24 15:30:03',
                'updated_at' => '2019-12-24 15:30:03',
                'deleted_at' => NULL,
                'name' => 'عسل جبلي سعودي',
                'quantity_type' => 1,
                'type' => 0,
                'material_type_id' => 1,
                'max_order' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'created_at' => '2019-12-24 15:30:36',
                'updated_at' => '2019-12-24 15:30:36',
                'deleted_at' => NULL,
                'name' => 'عسل جبلي ليبي',
                'quantity_type' => 1,
                'type' => 0,
                'material_type_id' => 1,
                'max_order' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'created_at' => '2019-12-24 15:33:06',
                'updated_at' => '2019-12-24 15:33:06',
                'deleted_at' => NULL,
                'name' => 'عسل جبلي زعتر',
                'quantity_type' => 1,
                'type' => 0,
                'material_type_id' => 1,
                'max_order' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'created_at' => '2019-12-24 15:37:27',
                'updated_at' => '2019-12-24 15:37:27',
                'deleted_at' => NULL,
                'name' => 'عسل جبلي مصري',
                'quantity_type' => 1,
                'type' => 0,
                'material_type_id' => 1,
                'max_order' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'created_at' => '2019-12-24 15:37:47',
                'updated_at' => '2019-12-24 15:37:47',
                'deleted_at' => NULL,
                'name' => 'عسل جبلي بري',
                'quantity_type' => 1,
                'type' => 0,
                'material_type_id' => 1,
                'max_order' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'created_at' => '2019-12-24 15:38:10',
                'updated_at' => '2019-12-24 15:38:10',
                'deleted_at' => NULL,
                'name' => 'عسل جبلي حضرمي',
                'quantity_type' => 1,
                'type' => 0,
                'material_type_id' => 1,
                'max_order' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'created_at' => '2019-12-24 15:38:38',
                'updated_at' => '2019-12-24 15:38:38',
                'deleted_at' => NULL,
                'name' => 'عسل جبلي دوعني',
                'quantity_type' => 1,
                'type' => 0,
                'material_type_id' => 1,
                'max_order' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'created_at' => '2019-12-24 15:39:05',
                'updated_at' => '2019-12-24 15:39:05',
                'deleted_at' => NULL,
                'name' => 'عسل نوارة البرسيم تصدير',
                'quantity_type' => 1,
                'type' => 0,
                'material_type_id' => 1,
                'max_order' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'created_at' => '2019-12-24 15:39:27',
                'updated_at' => '2019-12-24 15:39:27',
                'deleted_at' => NULL,
                'name' => 'عسل صحراوي تصدير',
                'quantity_type' => 1,
                'type' => 0,
                'material_type_id' => 1,
                'max_order' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'created_at' => '2019-12-24 15:39:52',
                'updated_at' => '2019-12-24 15:39:52',
                'deleted_at' => NULL,
                'name' => 'عسل حبة البركة تصدير',
                'quantity_type' => 1,
                'type' => 0,
                'material_type_id' => 1,
                'max_order' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'created_at' => '2019-12-24 15:40:21',
                'updated_at' => '2019-12-24 15:40:21',
                'deleted_at' => NULL,
                'name' => 'عسل بردقوش تصدير',
                'quantity_type' => 1,
                'type' => 0,
                'material_type_id' => 1,
                'max_order' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'created_at' => '2019-12-24 15:40:50',
                'updated_at' => '2019-12-24 15:40:50',
                'deleted_at' => NULL,
                'name' => 'عسل موالح تصدير',
                'quantity_type' => 1,
                'type' => 0,
                'material_type_id' => 1,
                'max_order' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'created_at' => '2019-12-24 15:41:15',
                'updated_at' => '2019-12-24 15:41:15',
                'deleted_at' => NULL,
                'name' => 'عسل بلدي تصدير',
                'quantity_type' => 1,
                'type' => 0,
                'material_type_id' => 1,
                'max_order' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'created_at' => '2019-12-24 15:41:40',
                'updated_at' => '2019-12-24 15:41:40',
                'deleted_at' => NULL,
                'name' => 'عسل نباتات طبيه',
                'quantity_type' => 1,
                'type' => 0,
                'material_type_id' => 1,
                'max_order' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'created_at' => '2019-12-24 15:42:08',
                'updated_at' => '2019-12-24 15:42:08',
                'deleted_at' => NULL,
                'name' => 'عسل كراويا',
                'quantity_type' => 1,
                'type' => 0,
                'material_type_id' => 1,
                'max_order' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'created_at' => '2019-12-24 15:42:33',
                'updated_at' => '2019-12-24 15:42:33',
                'deleted_at' => NULL,
                'name' => 'عسل ينسون تصدير',
                'quantity_type' => 1,
                'type' => 0,
                'material_type_id' => 1,
                'max_order' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'created_at' => '2019-12-24 15:42:55',
                'updated_at' => '2019-12-24 15:42:55',
                'deleted_at' => NULL,
                'name' => 'عسل ينسون محلي',
                'quantity_type' => 0,
                'type' => 0,
                'material_type_id' => 1,
                'max_order' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'created_at' => '2019-12-24 15:43:37',
                'updated_at' => '2019-12-24 15:43:37',
                'deleted_at' => NULL,
                'name' => 'عسل شمر',
                'quantity_type' => 1,
                'type' => 0,
                'material_type_id' => 1,
                'max_order' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'created_at' => '2019-12-24 15:44:05',
                'updated_at' => '2019-12-24 15:44:05',
                'deleted_at' => NULL,
                'name' => 'عسل دبس بلح',
                'quantity_type' => 1,
                'type' => 0,
                'material_type_id' => 1,
                'max_order' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'created_at' => '2019-12-24 15:44:47',
                'updated_at' => '2019-12-24 15:44:47',
                'deleted_at' => NULL,
                'name' => 'برطمان زجاج كيلو',
                'quantity_type' => 0,
                'type' => 1,
                'material_type_id' => 2,
                'max_order' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'created_at' => '2019-12-24 15:45:16',
                'updated_at' => '2019-12-24 15:45:16',
                'deleted_at' => NULL,
                'name' => 'برطمان زجاج 1/2ك',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 2,
                'max_order' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'created_at' => '2019-12-24 15:45:41',
                'updated_at' => '2019-12-24 15:45:41',
                'deleted_at' => NULL,
                'name' => 'برطمان زجاج 1/4ك',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 2,
                'max_order' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'created_at' => '2019-12-24 15:46:13',
                'updated_at' => '2019-12-24 15:46:13',
                'deleted_at' => NULL,
                'name' => 'غطاء مملكة النحل ك',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 3,
                'max_order' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'created_at' => '2019-12-24 15:46:35',
                'updated_at' => '2019-12-24 15:46:35',
                'deleted_at' => NULL,
                'name' => 'غطاء مملكة النحل 1/2ك',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 3,
                'max_order' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'created_at' => '2019-12-24 15:46:58',
                'updated_at' => '2019-12-24 15:46:58',
                'deleted_at' => NULL,
                'name' => 'غطاء مملكة النحل 1/4ك',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 3,
                'max_order' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'created_at' => '2019-12-24 15:47:25',
                'updated_at' => '2019-12-24 15:47:25',
                'deleted_at' => NULL,
                'name' => 'غطاء دهبي ك',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 3,
                'max_order' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'created_at' => '2019-12-24 15:47:47',
                'updated_at' => '2019-12-24 15:47:47',
                'deleted_at' => NULL,
                'name' => 'غطاء دهبي 1/2ك',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 3,
                'max_order' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'created_at' => '2019-12-24 15:48:09',
                'updated_at' => '2019-12-24 15:48:09',
                'deleted_at' => NULL,
                'name' => 'غطاء دهبي 1/4ك',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 3,
                'max_order' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'created_at' => '2019-12-24 15:48:39',
                'updated_at' => '2019-12-24 15:48:39',
                'deleted_at' => NULL,
                'name' => 'شرنك بلاستيك ك',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 4,
                'max_order' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'created_at' => '2019-12-24 15:49:05',
                'updated_at' => '2019-12-24 15:49:05',
                'deleted_at' => NULL,
                'name' => 'شرنك بلاستيك 1/2ك',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 4,
                'max_order' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'created_at' => '2019-12-24 15:49:32',
                'updated_at' => '2019-12-24 15:49:32',
                'deleted_at' => NULL,
                'name' => 'شرنك بلاستيك 1/4ك',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 4,
                'max_order' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'created_at' => '2019-12-24 15:51:29',
                'updated_at' => '2019-12-24 15:51:29',
                'deleted_at' => NULL,
                'name' => 'كرتون كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 6,
                'max_order' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'created_at' => '2019-12-24 15:51:51',
                'updated_at' => '2019-12-24 15:51:51',
                'deleted_at' => NULL,
                'name' => 'كرتون 1/2ك',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 6,
                'max_order' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'created_at' => '2019-12-24 15:52:10',
                'updated_at' => '2019-12-24 15:52:10',
                'deleted_at' => NULL,
                'name' => 'كرتون 1/4ك',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 6,
                'max_order' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'created_at' => '2019-12-25 11:16:28',
                'updated_at' => '2019-12-25 11:16:28',
                'deleted_at' => NULL,
                'name' => 'عسل بالغذاء للاطفال ك',
                'quantity_type' => 1,
                'type' => 0,
                'material_type_id' => 1,
                'max_order' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'created_at' => '2019-12-25 11:16:54',
                'updated_at' => '2019-12-25 11:16:54',
                'deleted_at' => NULL,
                'name' => 'عسل بالغذاء للاطفال 1/2ك',
                'quantity_type' => 1,
                'type' => 0,
                'material_type_id' => 1,
                'max_order' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'created_at' => '2019-12-25 11:17:41',
                'updated_at' => '2019-12-25 11:17:41',
                'deleted_at' => NULL,
                'name' => 'عسل بالشمع ك',
                'quantity_type' => 1,
                'type' => 0,
                'material_type_id' => 1,
                'max_order' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'created_at' => '2019-12-25 11:19:05',
                'updated_at' => '2019-12-25 11:19:05',
                'deleted_at' => NULL,
                'name' => 'عسل بالشمع 1/2ك',
                'quantity_type' => 1,
                'type' => 0,
                'material_type_id' => 1,
                'max_order' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'created_at' => '2019-12-25 11:23:37',
                'updated_at' => '2019-12-25 11:23:37',
                'deleted_at' => NULL,
                'name' => 'علبة عسل بالشمع 420جم',
                'quantity_type' => 1,
                'type' => 0,
                'material_type_id' => 1,
                'max_order' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'created_at' => '2019-12-25 11:24:52',
                'updated_at' => '2019-12-25 11:24:52',
                'deleted_at' => NULL,
                'name' => 'زيت المعالج',
                'quantity_type' => 1,
                'type' => 0,
                'material_type_id' => 1,
                'max_order' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'created_at' => '2019-12-25 11:25:09',
                'updated_at' => '2019-12-25 11:25:09',
                'deleted_at' => NULL,
                'name' => 'زيت الاطالة',
                'quantity_type' => 1,
                'type' => 0,
                'material_type_id' => 1,
                'max_order' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'created_at' => '2019-12-25 11:25:26',
                'updated_at' => '2019-12-25 11:25:26',
                'deleted_at' => NULL,
                'name' => 'زيت الفرد',
                'quantity_type' => 1,
                'type' => 0,
                'material_type_id' => 1,
                'max_order' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'created_at' => '2019-12-25 11:25:46',
                'updated_at' => '2019-12-25 11:25:46',
                'deleted_at' => NULL,
                'name' => 'اعشاب التخسيس',
                'quantity_type' => 1,
                'type' => 0,
                'material_type_id' => 1,
                'max_order' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'created_at' => '2019-12-25 11:26:08',
                'updated_at' => '2019-12-25 11:26:08',
                'deleted_at' => NULL,
                'name' => 'اعشاب السكر',
                'quantity_type' => 1,
                'type' => 0,
                'material_type_id' => 1,
                'max_order' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'created_at' => '2019-12-25 11:26:24',
                'updated_at' => '2019-12-25 11:26:24',
                'deleted_at' => NULL,
                'name' => 'اعشاب القولون',
                'quantity_type' => 0,
                'type' => 0,
                'material_type_id' => 1,
                'max_order' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'created_at' => '2019-12-25 11:26:47',
                'updated_at' => '2019-12-25 11:26:47',
                'deleted_at' => NULL,
                'name' => 'اعشاب الاملاح والحصوات',
                'quantity_type' => 1,
                'type' => 0,
                'material_type_id' => 1,
                'max_order' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'created_at' => '2019-12-25 11:27:30',
                'updated_at' => '2019-12-25 11:27:30',
                'deleted_at' => NULL,
                'name' => 'اعشاب الكحة',
                'quantity_type' => 1,
                'type' => 0,
                'material_type_id' => 1,
                'max_order' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'created_at' => '2019-12-25 11:28:26',
                'updated_at' => '2019-12-25 11:28:26',
                'deleted_at' => NULL,
                'name' => 'اعشاب التقوية الجنسية',
                'quantity_type' => 1,
                'type' => 0,
                'material_type_id' => 1,
                'max_order' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'created_at' => '2019-12-25 11:28:48',
                'updated_at' => '2019-12-25 11:28:48',
                'deleted_at' => NULL,
                'name' => 'خلطة زياده الوزن ك',
                'quantity_type' => 1,
                'type' => 0,
                'material_type_id' => 1,
                'max_order' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'created_at' => '2019-12-25 11:29:09',
                'updated_at' => '2019-12-25 11:29:09',
                'deleted_at' => NULL,
                'name' => 'خلطة زيادة الوزن 1/2ك',
                'quantity_type' => 1,
                'type' => 0,
                'material_type_id' => 1,
                'max_order' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'created_at' => '2019-12-25 11:29:36',
                'updated_at' => '2019-12-25 11:29:36',
                'deleted_at' => NULL,
                'name' => 'دبس بلح',
                'quantity_type' => 1,
                'type' => 0,
                'material_type_id' => 1,
                'max_order' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'created_at' => '2019-12-25 11:31:45',
                'updated_at' => '2019-12-25 11:32:51',
                'deleted_at' => NULL,
                'name' => 'علبة كرتونه كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 7,
                'max_order' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'created_at' => '2019-12-25 11:32:07',
                'updated_at' => '2019-12-25 11:32:07',
                'deleted_at' => NULL,
                'name' => 'علبة كرتون 1/2ك',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 7,
                'max_order' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'created_at' => '2019-12-25 11:32:43',
                'updated_at' => '2019-12-25 11:32:43',
                'deleted_at' => NULL,
                'name' => 'علبة كرتون 1/4ك',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 7,
                'max_order' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'created_at' => '2019-12-26 08:17:51',
                'updated_at' => '2019-12-26 08:20:30',
                'deleted_at' => NULL,
                'name' => 'عسل موالح',
                'quantity_type' => 0,
                'type' => 0,
                'material_type_id' => 1,
                'max_order' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'created_at' => '2019-12-30 08:47:35',
                'updated_at' => '2019-12-30 08:47:35',
                'deleted_at' => NULL,
                'name' => 'خامة',
                'quantity_type' => 0,
                'type' => 0,
                'material_type_id' => 1,
                'max_order' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'created_at' => '2019-12-30 15:45:30',
                'updated_at' => '2019-12-30 15:45:30',
                'deleted_at' => NULL,
                'name' => 'عسل جبلى مصرى 80',
                'quantity_type' => 0,
                'type' => 0,
                'material_type_id' => 1,
                'max_order' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'created_at' => '2019-12-31 09:33:05',
                'updated_at' => '2019-12-31 09:33:05',
                'deleted_at' => NULL,
                'name' => 'استيكر نواره محلي كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'created_at' => '2019-12-31 10:40:39',
                'updated_at' => '2019-12-31 10:40:39',
                'deleted_at' => NULL,
                'name' => 'علبة جبلي مصري كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 7,
                'max_order' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'created_at' => '2019-12-31 10:41:05',
                'updated_at' => '2019-12-31 10:41:05',
                'deleted_at' => NULL,
                'name' => 'علبة جبلي مصري 1/2كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 7,
                'max_order' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'created_at' => '2019-12-31 10:41:24',
                'updated_at' => '2019-12-31 10:41:24',
                'deleted_at' => NULL,
                'name' => 'علبة جبلي مصري 1/4كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 7,
                'max_order' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'created_at' => '2019-12-31 10:41:49',
                'updated_at' => '2019-12-31 10:41:49',
                'deleted_at' => NULL,
                'name' => 'علبة جبلي سعودي 1/2 كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 7,
                'max_order' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'created_at' => '2019-12-31 10:42:09',
                'updated_at' => '2019-12-31 10:42:09',
                'deleted_at' => NULL,
                'name' => 'علبة جبلي سعودي 1/4كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 7,
                'max_order' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'created_at' => '2019-12-31 10:42:27',
                'updated_at' => '2019-12-31 10:42:27',
                'deleted_at' => NULL,
                'name' => 'علبة جبلي ليبي 1/2كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 7,
                'max_order' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'created_at' => '2019-12-31 10:42:45',
                'updated_at' => '2019-12-31 10:42:45',
                'deleted_at' => NULL,
                'name' => 'علبة جبلي ليبي 1/4كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 7,
                'max_order' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'created_at' => '2019-12-31 10:43:04',
                'updated_at' => '2019-12-31 10:43:04',
                'deleted_at' => NULL,
                'name' => 'علبة جبلي مرحنون 1/2كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 7,
                'max_order' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'created_at' => '2019-12-31 10:43:27',
                'updated_at' => '2019-12-31 10:43:27',
                'deleted_at' => NULL,
                'name' => 'علبة جبلي مرحنون 1/4كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 7,
                'max_order' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'created_at' => '2019-12-31 10:43:50',
                'updated_at' => '2019-12-31 10:43:50',
                'deleted_at' => NULL,
                'name' => 'علبة جبلي زعتر 1/2كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 7,
                'max_order' => NULL,
            ),
            76 => 
            array (
                'id' => 77,
                'created_at' => '2019-12-31 10:44:11',
                'updated_at' => '2019-12-31 10:44:11',
                'deleted_at' => NULL,
                'name' => 'علبة جبلي زعتر 1/4 كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 7,
                'max_order' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'created_at' => '2019-12-31 10:44:33',
                'updated_at' => '2019-12-31 10:44:33',
                'deleted_at' => NULL,
                'name' => 'علبة جبلي بري كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 7,
                'max_order' => NULL,
            ),
            78 => 
            array (
                'id' => 79,
                'created_at' => '2019-12-31 10:44:51',
                'updated_at' => '2019-12-31 10:44:51',
                'deleted_at' => NULL,
                'name' => 'علبة جبلي بري 1/2كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 7,
                'max_order' => NULL,
            ),
            79 => 
            array (
                'id' => 80,
                'created_at' => '2019-12-31 10:45:08',
                'updated_at' => '2019-12-31 10:45:08',
                'deleted_at' => NULL,
                'name' => 'علبة جبلي بري 1/4كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 7,
                'max_order' => NULL,
            ),
            80 => 
            array (
                'id' => 81,
                'created_at' => '2019-12-31 10:45:39',
                'updated_at' => '2019-12-31 10:45:39',
                'deleted_at' => NULL,
                'name' => 'علبة جبلي سدر حضرمي 1/2ك',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 7,
                'max_order' => NULL,
            ),
            81 => 
            array (
                'id' => 82,
                'created_at' => '2019-12-31 10:46:03',
                'updated_at' => '2019-12-31 10:46:03',
                'deleted_at' => NULL,
                'name' => 'علبة جبلي سدر حضرمي 1/4 كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 7,
                'max_order' => NULL,
            ),
            82 => 
            array (
                'id' => 83,
                'created_at' => '2019-12-31 10:46:32',
                'updated_at' => '2019-12-31 10:46:32',
                'deleted_at' => NULL,
                'name' => 'علبة جبلي سدر دوعني 1/2كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 7,
                'max_order' => NULL,
            ),
            83 => 
            array (
                'id' => 84,
                'created_at' => '2019-12-31 10:46:54',
                'updated_at' => '2019-12-31 10:46:54',
                'deleted_at' => NULL,
                'name' => 'علبة جبلي سدر دوعني 1/4 كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 7,
                'max_order' => NULL,
            ),
            84 => 
            array (
                'id' => 85,
                'created_at' => '2019-12-31 10:47:13',
                'updated_at' => '2019-12-31 10:47:13',
                'deleted_at' => NULL,
                'name' => 'علبة جبلي غابات 1/4 كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 7,
                'max_order' => NULL,
            ),
            85 => 
            array (
                'id' => 86,
                'created_at' => '2019-12-31 10:47:42',
                'updated_at' => '2019-12-31 10:47:42',
                'deleted_at' => NULL,
                'name' => 'علبة  خلطة زيادة الوزن كيلو',
                'quantity_type' => 0,
                'type' => 1,
                'material_type_id' => 7,
                'max_order' => NULL,
            ),
            86 => 
            array (
                'id' => 87,
                'created_at' => '2019-12-31 10:48:02',
                'updated_at' => '2019-12-31 10:48:02',
                'deleted_at' => NULL,
                'name' => 'علبة خلطة زياده الوزن 1/2كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 7,
                'max_order' => NULL,
            ),
            87 => 
            array (
                'id' => 88,
                'created_at' => '2019-12-31 10:49:15',
                'updated_at' => '2019-12-31 10:49:15',
                'deleted_at' => NULL,
                'name' => 'برطمان كلبس 1/2كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 2,
                'max_order' => NULL,
            ),
            88 => 
            array (
                'id' => 89,
                'created_at' => '2019-12-31 10:49:32',
                'updated_at' => '2019-12-31 10:49:32',
                'deleted_at' => NULL,
                'name' => 'برطمان كلبس 1/4كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 2,
                'max_order' => NULL,
            ),
            89 => 
            array (
                'id' => 90,
                'created_at' => '2019-12-31 10:50:11',
                'updated_at' => '2019-12-31 10:50:11',
                'deleted_at' => NULL,
                'name' => 'استيكر نوارة محلي 1/2كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 4,
                'max_order' => NULL,
            ),
            90 => 
            array (
                'id' => 91,
                'created_at' => '2019-12-31 10:50:38',
                'updated_at' => '2019-12-31 10:50:38',
                'deleted_at' => NULL,
                'name' => 'استيكر نواره محلي 1/4كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            91 => 
            array (
                'id' => 92,
                'created_at' => '2019-12-31 10:50:58',
                'updated_at' => '2019-12-31 10:50:58',
                'deleted_at' => NULL,
                'name' => 'استيكر صحراوي محلي كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            92 => 
            array (
                'id' => 93,
                'created_at' => '2019-12-31 10:51:21',
                'updated_at' => '2019-12-31 10:51:21',
                'deleted_at' => NULL,
                'name' => 'استيكر صحراوي محلي 1/2كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            93 => 
            array (
                'id' => 94,
                'created_at' => '2019-12-31 10:51:48',
                'updated_at' => '2019-12-31 10:51:48',
                'deleted_at' => NULL,
                'name' => 'استيكر حبة البركة محلي كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            94 => 
            array (
                'id' => 95,
                'created_at' => '2019-12-31 10:52:11',
                'updated_at' => '2019-12-31 10:52:11',
                'deleted_at' => NULL,
                'name' => 'استيكر حبة البركة محلي 1/4كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            95 => 
            array (
                'id' => 96,
                'created_at' => '2019-12-31 10:52:44',
                'updated_at' => '2019-12-31 10:52:44',
                'deleted_at' => NULL,
                'name' => 'استيكر جبة البركه محلي 1/2كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            96 => 
            array (
                'id' => 97,
                'created_at' => '2019-12-31 10:53:16',
                'updated_at' => '2019-12-31 10:53:16',
                'deleted_at' => NULL,
                'name' => 'استيكر بردقوش محلي كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            97 => 
            array (
                'id' => 98,
                'created_at' => '2019-12-31 10:53:41',
                'updated_at' => '2019-12-31 10:53:41',
                'deleted_at' => NULL,
                'name' => 'استيكر بردقوش محلي 1/2كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            98 => 
            array (
                'id' => 99,
                'created_at' => '2019-12-31 10:54:08',
                'updated_at' => '2019-12-31 10:54:08',
                'deleted_at' => NULL,
                'name' => 'استيكر موالح محلي كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            99 => 
            array (
                'id' => 100,
                'created_at' => '2019-12-31 10:54:31',
                'updated_at' => '2019-12-31 10:54:31',
                'deleted_at' => NULL,
                'name' => 'استيكر موالح محلي 1/2كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            100 => 
            array (
                'id' => 101,
                'created_at' => '2019-12-31 10:54:52',
                'updated_at' => '2019-12-31 10:54:52',
                'deleted_at' => NULL,
                'name' => 'استيكر بلح محلي كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            101 => 
            array (
                'id' => 102,
                'created_at' => '2019-12-31 10:55:14',
                'updated_at' => '2019-12-31 10:55:14',
                'deleted_at' => NULL,
                'name' => 'استيكر بلح محلي 1/2كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            102 => 
            array (
                'id' => 103,
                'created_at' => '2019-12-31 11:00:22',
                'updated_at' => '2019-12-31 11:01:23',
                'deleted_at' => NULL,
                'name' => 'استيكر جبلي سعودي 1/2كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            103 => 
            array (
                'id' => 104,
                'created_at' => '2019-12-31 11:00:38',
                'updated_at' => '2019-12-31 11:01:14',
                'deleted_at' => NULL,
                'name' => 'استيكر جبلي  سعودي 1/4كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            104 => 
            array (
                'id' => 105,
                'created_at' => '2019-12-31 11:01:04',
                'updated_at' => '2019-12-31 11:01:04',
                'deleted_at' => NULL,
                'name' => 'استيكر جبلي ليبي 1/2كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            105 => 
            array (
                'id' => 106,
                'created_at' => '2019-12-31 11:01:47',
                'updated_at' => '2019-12-31 11:01:47',
                'deleted_at' => NULL,
                'name' => 'استيكر جبلي ليبي 1/4 كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            106 => 
            array (
                'id' => 107,
                'created_at' => '2019-12-31 11:02:10',
                'updated_at' => '2019-12-31 11:02:10',
                'deleted_at' => NULL,
                'name' => 'استيكر جبلي مر حنون 1/2كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            107 => 
            array (
                'id' => 108,
                'created_at' => '2019-12-31 11:02:32',
                'updated_at' => '2019-12-31 11:02:32',
                'deleted_at' => NULL,
                'name' => 'استيكر جبلي مر حنون 1/4كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            108 => 
            array (
                'id' => 109,
                'created_at' => '2019-12-31 11:02:53',
                'updated_at' => '2019-12-31 11:02:53',
                'deleted_at' => NULL,
                'name' => 'استيكر جبلي زعتر 1/2كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            109 => 
            array (
                'id' => 110,
                'created_at' => '2019-12-31 11:03:25',
                'updated_at' => '2019-12-31 11:03:25',
                'deleted_at' => NULL,
                'name' => 'استيكر جبلي زعتر 1/4كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            110 => 
            array (
                'id' => 111,
                'created_at' => '2019-12-31 11:03:48',
                'updated_at' => '2019-12-31 11:03:48',
                'deleted_at' => NULL,
                'name' => 'استيكر جبلي مصري كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            111 => 
            array (
                'id' => 112,
                'created_at' => '2019-12-31 11:04:08',
                'updated_at' => '2019-12-31 11:04:08',
                'deleted_at' => NULL,
                'name' => 'استيكر جبلي مصري 1/2كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            112 => 
            array (
                'id' => 113,
                'created_at' => '2019-12-31 11:04:32',
                'updated_at' => '2019-12-31 11:04:32',
                'deleted_at' => NULL,
                'name' => 'استيكر جبلي مصري 1/4 كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            113 => 
            array (
                'id' => 114,
                'created_at' => '2019-12-31 11:04:51',
                'updated_at' => '2019-12-31 11:04:51',
                'deleted_at' => NULL,
                'name' => 'استيكر جبلي بري كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            114 => 
            array (
                'id' => 115,
                'created_at' => '2019-12-31 11:05:18',
                'updated_at' => '2019-12-31 11:05:18',
                'deleted_at' => NULL,
                'name' => 'استيكر جبلي بري 1/2كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            115 => 
            array (
                'id' => 116,
                'created_at' => '2019-12-31 11:05:36',
                'updated_at' => '2019-12-31 11:05:36',
                'deleted_at' => NULL,
                'name' => 'استيكر جبلي بري 1/4 كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            116 => 
            array (
                'id' => 117,
                'created_at' => '2019-12-31 11:06:11',
                'updated_at' => '2019-12-31 11:06:11',
                'deleted_at' => NULL,
                'name' => 'استيكر جبلي سدر حضرمي 1/2كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            117 => 
            array (
                'id' => 118,
                'created_at' => '2019-12-31 11:06:38',
                'updated_at' => '2019-12-31 11:06:38',
                'deleted_at' => NULL,
                'name' => 'استيكر جبلي سدر جضرمي 1/4 كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            118 => 
            array (
                'id' => 119,
                'created_at' => '2019-12-31 11:07:02',
                'updated_at' => '2019-12-31 11:07:02',
                'deleted_at' => NULL,
                'name' => 'استيكر جبلي سدر دوعني 1/2كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            119 => 
            array (
                'id' => 120,
                'created_at' => '2019-12-31 11:07:23',
                'updated_at' => '2019-12-31 11:07:23',
                'deleted_at' => NULL,
                'name' => 'استيكر جبلي سدر دوعني 1/4 كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            120 => 
            array (
                'id' => 121,
                'created_at' => '2019-12-31 11:07:54',
                'updated_at' => '2019-12-31 11:07:54',
                'deleted_at' => NULL,
                'name' => 'استيكر جبلي غابات 1/4كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            121 => 
            array (
                'id' => 122,
                'created_at' => '2019-12-31 11:08:42',
                'updated_at' => '2019-12-31 11:08:42',
                'deleted_at' => NULL,
                'name' => 'استيكر خلطة زياده الوزن كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            122 => 
            array (
                'id' => 123,
                'created_at' => '2019-12-31 11:09:18',
                'updated_at' => '2019-12-31 11:09:50',
                'deleted_at' => '2019-12-31 11:09:50',
                'name' => 'استيكر خبطة زياده الوزن كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            123 => 
            array (
                'id' => 124,
                'created_at' => '2019-12-31 11:13:33',
                'updated_at' => '2019-12-31 11:13:33',
                'deleted_at' => NULL,
                'name' => 'استيكر نواره تصدير كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            124 => 
            array (
                'id' => 125,
                'created_at' => '2019-12-31 11:13:58',
                'updated_at' => '2019-12-31 11:13:58',
                'deleted_at' => NULL,
                'name' => 'استيكر نوارة تصدير 1/2كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            125 => 
            array (
                'id' => 126,
                'created_at' => '2019-12-31 11:14:37',
                'updated_at' => '2019-12-31 11:14:37',
                'deleted_at' => NULL,
                'name' => 'استيكر نباتات طبية كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            126 => 
            array (
                'id' => 127,
                'created_at' => '2019-12-31 11:14:57',
                'updated_at' => '2019-12-31 11:14:57',
                'deleted_at' => NULL,
                'name' => 'استيكر نباتات طبية 1/2 كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            127 => 
            array (
                'id' => 128,
                'created_at' => '2019-12-31 11:15:20',
                'updated_at' => '2019-12-31 11:15:20',
                'deleted_at' => NULL,
                'name' => 'استيكر صحراوي تصدير كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            128 => 
            array (
                'id' => 129,
                'created_at' => '2019-12-31 11:15:42',
                'updated_at' => '2019-12-31 11:15:42',
                'deleted_at' => NULL,
                'name' => 'استيكر صحراوي تصدير 1/2 كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            129 => 
            array (
                'id' => 130,
                'created_at' => '2019-12-31 11:16:11',
                'updated_at' => '2019-12-31 11:16:11',
                'deleted_at' => NULL,
                'name' => 'استيكر حبة البركة تصدير كيلو',
                'quantity_type' => 0,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            130 => 
            array (
                'id' => 131,
                'created_at' => '2019-12-31 11:17:48',
                'updated_at' => '2019-12-31 11:17:48',
                'deleted_at' => NULL,
                'name' => 'استيكر بردقوش تصدير كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            131 => 
            array (
                'id' => 132,
                'created_at' => '2019-12-31 11:18:33',
                'updated_at' => '2019-12-31 11:18:33',
                'deleted_at' => NULL,
                'name' => 'استيكر بردقوش تصدير 1/2كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            132 => 
            array (
                'id' => 133,
                'created_at' => '2019-12-31 11:20:40',
                'updated_at' => '2019-12-31 11:20:40',
                'deleted_at' => NULL,
                'name' => 'استيكر موالح تصدير كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            133 => 
            array (
                'id' => 134,
                'created_at' => '2019-12-31 11:21:26',
                'updated_at' => '2019-12-31 11:21:26',
                'deleted_at' => NULL,
                'name' => 'استيكر موالح تصدير 1/2كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            134 => 
            array (
                'id' => 135,
                'created_at' => '2019-12-31 11:22:07',
                'updated_at' => '2019-12-31 11:22:07',
                'deleted_at' => NULL,
                'name' => 'استيكر بلدي تصدير كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            135 => 
            array (
                'id' => 136,
                'created_at' => '2019-12-31 11:42:50',
                'updated_at' => '2019-12-31 11:42:50',
                'deleted_at' => NULL,
                'name' => 'استيكر عسل بالمكسرات 1/2كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            136 => 
            array (
                'id' => 137,
                'created_at' => '2019-12-31 11:43:10',
                'updated_at' => '2019-12-31 11:43:10',
                'deleted_at' => NULL,
                'name' => 'استيكر عسل بالمكسرات 1/4 كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            137 => 
            array (
                'id' => 138,
                'created_at' => '2019-12-31 11:44:03',
                'updated_at' => '2019-12-31 11:44:03',
                'deleted_at' => NULL,
                'name' => 'استيكر بالغذاء للاطفال كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            138 => 
            array (
                'id' => 139,
                'created_at' => '2019-12-31 11:44:31',
                'updated_at' => '2019-12-31 11:44:31',
                'deleted_at' => NULL,
                'name' => 'استيكر بالغذاء للاطفال 1/2كيلو',
                'quantity_type' => 1,
                'type' => 1,
                'material_type_id' => 5,
                'max_order' => NULL,
            ),
            139 => 
            array (
                'id' => 140,
                'created_at' => '2020-01-02 07:39:33',
                'updated_at' => '2020-01-02 07:39:33',
                'deleted_at' => NULL,
                'name' => 'خامة تيست',
                'quantity_type' => 0,
                'type' => 0,
                'material_type_id' => 1,
                'max_order' => 50,
            ),
        ));
        
        
    }
}